import type { ForeignData } from "./ForeignData";
import type { Identifiers } from "./Identifiers";
import type { LeadershipSkills } from "./LeadershipSkills";
import type { Legalities } from "./Legalities";
import type { PurchaseUrls } from "./PurchaseUrls";
import type { RelatedCards } from "./RelatedCards";
import type { Rulings } from "./Rulings";
import type { SourceProducts } from "./SourceProducts";

export type CardToken = {
    artist?: string;
    artistIds?: string[];
    asciiName?: string;
    availability: string[];
    boosterTypes?: string[];
    borderColor: string;
    cardParts?: string[];
    colorIdentity: string[];
    colorIndicator?: string[];
    colors: string[];
    edhrecSaltiness?: number;
    faceName?: string;
    faceFlavorName?: string;
    finishes: string[];
    flavorName?: string;
    flavorText?: string;
    frameEffects?: string[];
    frameVersion: string;
    hasFoil: boolean;
    hasNonFoil: boolean;
    identifiers: Identifiers;
    isFullArt?: boolean;
    isFunny?: boolean;
    isOnlineOnly?: boolean;
    isOversized?: boolean;
    isPromo?: boolean;
    isReprint?: boolean;
    isTextless?: boolean;
    keywords?: string[];
    language: string;
    layout: string;
    loyalty?: string;
    manaCost?: string;
    name: string;
    number: string;
    orientation?: string;
    originalText?: string;
    originalType?: string;
    otherFaceIds?: string[];
    power?: string;
    promoTypes?: string[];
    relatedCards?: RelatedCards;
    reverseRelated?: string[];
    securityStamp?: string;
    setCode: string;
    side?: string;
    signature?: string;
    sourceProducts?: string[];
    subsets?: string[];
    subtypes: string[];
    supertypes: string[];
    text?: string;
    toughness?: string;
    type: string;
    types: string[];
    uuid: string;
    watermark?: string;
};

export type CardSet = {
    artist?: string;
    artistIds?: string[];
    asciiName?: string;
    attractionLights?: number[];
    availability: string[];
    boosterTypes?: string[];
    borderColor: string;
    cardParts?: string[];
    colorIdentity: string[];
    colorIndicator?: string[];
    colors: string[];
    convertedManaCost: number;
    defense?: string;
    duelDeck?: string;
    edhrecRank?: number;
    edhrecSaltiness?: number;
    faceConvertedManaCost?: number;
    faceFlavorName?: string;
    faceManaValue?: number;
    faceName?: string;
    finishes: string[];
    flavorName?: string;
    flavorText?: string;
    foreignData?: ForeignData[];
    frameEffects?: string[];
    frameVersion: string;
    hand?: string;
    hasAlternativeDeckLimit?: boolean;
    hasContentWarning?: boolean;
    hasFoil: boolean;
    hasNonFoil: boolean;
    identifiers: Identifiers;
    isAlternative?: boolean;
    isFullArt?: boolean;
    isFunny?: boolean;
    isGameChanger?: boolean;
    isOnlineOnly?: boolean;
    isOversized?: boolean;
    isPromo?: boolean;
    isRebalanced?: boolean;
    isReprint?: boolean;
    isReserved?: boolean;
    isStarter?: boolean;
    isStorySpotlight?: boolean;
    isTextless?: boolean;
    isTimeshifted?: boolean;
    keywords?: string[];
    language: string;
    layout: string;
    leadershipSkills?: LeadershipSkills;
    legalities: Legalities;
    life?: string;
    loyalty?: string;
    manaCost?: string;
    manaValue: number;
    name: string;
    number: string;
    originalPrintings?: string[];
    originalReleaseDate?: string;
    originalText?: string;
    originalType?: string;
    otherFaceIds?: string[];
    power?: string;
    printings?: string[];
    promoTypes?: string[];
    purchaseUrls: PurchaseUrls;
    rarity: string;
    relatedCards?: RelatedCards;
    rebalancedPrintings?: string[];
    rulings?: Rulings[];
    securityStamp?: string;
    setCode: string;
    side?: string;
    signature?: string;
    sourceProducts?: SourceProducts;
    subsets?: string[];
    subtypes: string[];
    supertypes: string[];
    text?: string;
    toughness?: string;
    type: string;
    types: string[];
    uuid: string;
    variations?: string[];
    watermark?: string;
};

export type CardSetDeck = {
    count: number;
    isFoil?: boolean;
    uuid: string;
};
