import type { BoosterConfig } from "./Booster";
import type { CardSet, CardToken } from "./Card";
import type { DeckSet } from "./DeckSet";
import type { SealedProduct } from "./SealedProduct";
import type { Translations } from "./Translations";

export type Set = {
    baseSetSize: number;
    block?: string;
    booster?: Record<string, BoosterConfig>;
    cards: CardSet[];
    cardsphereSetId?: number;
    code: string;
    codeV3?: string;
    decks?: DeckSet[];
    isForeignOnly?: boolean;
    isFoilOnly: boolean;
    isNonFoilOnly?: boolean;
    isOnlineOnly: boolean;
    isPaperOnly?: boolean;
    isPartialPreview?: boolean;
    keyruneCode: string;
    languages?: string[];
    mcmId?: number;
    mcmIdExtras?: number;
    mcmName?: string;
    mtgoCode?: string;
    name: string;
    parentCode?: string;
    releaseDate: string;
    sealedProduct?: SealedProduct[];
    tcgplayerGroupId?: number;
    tokens: CardToken[];
    tokenSetCode?: string;
    totalSetSize: number;
    translations: Translations;
    type: string;
};
